public class LeadTriggerHandler {
    public static String blablabla(){
        System.debug('test');
        System.debug('second comment');
        //3313
        //new comment
        Integer k = 0;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        k = k+1;
        //all work well  12334
        return 'ok';
    }


}
