public with sharing class SomeClass {

    public static void toDo(){
        System.debug('Alert for code scan');
        Integer i = 0;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        i = i+1;
        System.debug('i='+i);
    }
}