# Unique name for this workflow
name: Manual Run Test

# Definition when the workflow should run
on:
  workflow_dispatch:
    branches: [ main ]
    paths:
      - 'force-app/**'


# Jobs to be executed
jobs:
      - name: 'Run all tests'
       run: |
          echo ${{env.APEX_TESTS}}
          sfdx apex run test

