name: Deploy integration branch to INT

on:
  push:
    branches: [ development ]
    paths:
      - 'force-app/**'


jobs:

  run-pmd-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: 'Run PMD scan'
        uses: pmd/pmd-github-action@v1.4.0
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'force-app'
          rulesets: 'ruleset.xml'
          
      - name: 'Check for PMD violations'
        if: steps.pmd.outputs.violations != 0
        run: exit 1

####################################
  validate-by-codescan:
    runs-on: ubuntu-latest
    needs: run-pmd-scan
    permissions:
      security-events: write
    steps:

      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install CLI'
        run: npm run force:cli

      - name: 'Prepare sfdx git delta'
        run: npm run prepare:delta

      - name: 'Prepare scaner'
        run: npm run prepare:scaner

      - name: 'Populate auth file with SFDX_URL secret of integration org'
        shell: bash
        run: |
          echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

      - name: 'Run Auth Int'
        run: npm run force:auth

      - name: 'Run Scaner'
        run: npm run scaner:run

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: changed-sources/apexScanResults.sarif

  #########################################
  deploy-branch-to-int-tests:
    runs-on: ubuntu-latest
    needs: validate-by-codescan
    steps:

      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install CLI'
        run: npm run force:cli

      - name: 'Prepare delta for changes'
        run: npm run prepare:delta

      - name: 'Populate auth file with SFDX_URL secret of the integration and staging orgs'
        shell: bash
        run: |
          echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

      - name: 'Run Auth Int'
        run: npm run force:auth

      - name: 'Deploy the entire branch to Integration org'
        run: npm run force:deploy
